"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { GptMark } from "@/components/GptMark";
import { LoginForm } from "@/components/LoginForm";

const story = [
  { eyebrow: "01 · 함께 기록", title: "오늘 함께한 곳을\n가볍게 남겨요.", description: "장소와 사진, 한마디면 충분해요. 우리가 좋아했던 공간을 잊지 않도록." },
  { eyebrow: "02 · AI 장소 추천", title: "기록 속에서\n둘의 취향을 발견해요.", description: "조용한 공간, 오래 머문 카페, 좋아한 분위기. 쌓인 기록을 읽어 닮은 장소를 제안해요." },
  { eyebrow: "03 · AI 코스 추천", title: "한 장소에서 시작해도\n데이트가 완성돼요.", description: "선택한 장소의 분위기와 이동 거리를 함께 살펴, 코스에 자연스럽게 이어질 다음 장소를 추천해요." },
  { eyebrow: "04 · 우리의 캘린더", title: "함께한 하루를\n언제든 다시 꺼내봐요.", description: "그날의 장소와 사진, 한마디가 하나의 데이트로 모이고 다시 다음 추천의 취향이 돼요." },
];

function GoogleMark() {
  return <svg viewBox="0 0 48 48" aria-hidden className="h-[18px] w-[18px]"><path fill="#4285F4" d="M45.12 24.5c0-1.56-.14-3.06-.4-4.5H24v8.51h11.84c-.51 2.75-2.06 5.08-4.39 6.64v5.52h7.11c4.16-3.83 6.56-9.47 6.56-16.17z" /><path fill="#34A853" d="M24 46c5.94 0 10.92-1.97 14.56-5.33l-7.11-5.52c-1.97 1.32-4.49 2.1-7.45 2.1-5.73 0-10.58-3.87-12.31-9.07H4.34v5.7C7.96 41.07 15.4 46 24 46z" /><path fill="#FBBC05" d="M11.69 28.18A12.6 12.6 0 0 1 11 24c0-1.45.25-2.86.69-4.18v-5.7H4.34A22 22 0 0 0 2 24c0 3.55.85 6.91 2.34 9.88l7.35-5.7z" /><path fill="#EA4335" d="M24 10.75c3.23 0 6.13 1.11 8.41 3.29l6.31-6.31C34.91 4.18 29.93 2 24 2c-8.6 0-16.04 4.93-19.66 12.12l7.35 5.7c1.73-5.2 6.58-9.07 12.31-9.07z" /></svg>;
}

function RecordScene() {
  return <div className="mx-auto w-full max-w-[430px]"><p className="mb-3 text-center text-[11px] font-semibold text-muted-3">함께 기록한 장소</p><div className="overflow-hidden rounded-[26px] bg-white shadow-[0_28px_60px_-38px_rgba(42,61,59,0.55)] ring-1 ring-border"><div className="relative h-48 overflow-hidden bg-[#e7dfd2]"><img src="/landing-pompidou.jpg" alt="퐁피두센터 한화 전시에서 남긴 기록" className="h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-black/35 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold text-accent backdrop-blur">전시</span><span className="absolute bottom-4 left-4 text-xs font-medium text-white">2026.07.01</span></div><div className="p-5"><div className="min-w-0"><h3 className="truncate text-lg font-extrabold">퐁피두센터 한화</h3><p className="mt-1 truncate text-xs text-muted-2">서울 영등포구 63로 50</p></div><p className="mt-4 rounded-2xl bg-[#faf7f1] px-4 py-3 text-[12px] leading-6 text-[#575149]">“여의도에서 파리를 느끼다”</p><div className="mt-3 flex items-center justify-between"><span className="text-[12px] font-bold text-[#a68452]">★★★★★ <b className="ml-1">5.0</b></span><span className="text-[10px] font-semibold text-muted-3">date.log에 남긴 장소</span></div></div></div></div>;
}

function PlaceRecommendScene() {
  const cards = [["작은빛 전시관", "전시", "둘이 자주 고른 조용한 공간과 감성적인 분위기가 닮았어요."], ["온화한 정원", "산책", "카페에서 걸어서 8분, 늦은 오후 코스에 자연스럽게 이어져요."], ["서촌의 밤", "바", "대화하기 좋은 작은 공간을 선호한 기록을 반영했어요."]];
  return <div className="mx-auto w-full max-w-[470px]"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#10a37f] text-white"><GptMark className="h-5 w-5" /></span><div><p className="text-xs font-extrabold">이런 곳은 어때요?</p><p className="text-[10px] text-[#39816f]">우리의 취향 기반 AI 추천</p></div></div><span className="text-[10px] text-muted-3">서촌 주변</span></div><div className="space-y-2.5">{cards.map(([name, category, reason], index) => <div key={name} className={`rounded-[20px] bg-white p-4 ring-1 transition ${index === 0 ? "ring-[#10a37f]/40 shadow-[0_18px_40px_-32px_rgba(16,163,127,.8)]" : "ring-border"}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="rounded-full bg-[#f2eadc] px-2.5 py-1 text-[9px] font-bold">{category}</span><h3 className="text-sm font-extrabold">{name}</h3></div><span className="text-[10px] text-muted-3">{index === 0 ? "420m" : index === 1 ? "610m" : "850m"}</span></div><p className="mt-2 text-[11px] leading-5 text-muted-2">{reason}</p></div>)}</div></div>;
}

function CourseScene() {
  const stops = [["1", "소소한 식탁", "맛집"], ["2", "모노크림", "카페"], ["✦", "작은빛 전시관", "AI 추천"]];
  return <div className="mx-auto w-full max-w-[470px] rounded-[26px] bg-white p-5 shadow-[0_28px_60px_-40px_rgba(42,61,59,.55)] ring-1 ring-border sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold text-muted-3">늦여름 서촌 데이트</p><h3 className="mt-1 text-lg font-extrabold">맛있는 점심부터 작은 전시까지</h3></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#10a37f] text-white"><GptMark className="h-4 w-4" /></span></div><div className="relative mt-6 space-y-3 before:absolute before:bottom-5 before:left-[17px] before:top-5 before:w-px before:bg-accent/20">{stops.map(([number, name, category], index) => <div key={name} className={`relative z-10 flex items-center gap-3 rounded-2xl p-3.5 ${index === 2 ? "bg-[#edf9f4] ring-1 ring-[#10a37f]/25" : "bg-[#faf7f1]"}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[11px] font-extrabold ${index === 2 ? "bg-[#10a37f] text-white" : "bg-white text-accent ring-1 ring-border"}`}>{index === 2 ? <GptMark className="h-4 w-4" /> : number}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{name}</p><p className={`mt-0.5 text-[10px] ${index === 2 ? "font-semibold text-[#24735f]" : "text-muted-3"}`}>{category}</p></div>{index === 2 && <span className="rounded-full bg-white px-2.5 py-1 text-[9px] font-bold text-[#24735f]">코스에 추가</span>}</div>)}</div><p className="mt-4 rounded-2xl bg-accent-soft/55 px-4 py-3 text-[10px] leading-5 text-accent"><b>추천 이유</b> · 점심과 카페 뒤에 조용한 전시를 더하면 둘이 좋아하는 느린 오후 코스가 완성돼요.</p></div>;
}

function CalendarScene() {
  const days = Array.from({ length: 30 }, (_, i) => i + 1);
  return <div className="mx-auto w-full max-w-[470px] rounded-[26px] bg-white p-5 shadow-[0_28px_60px_-40px_rgba(42,61,59,.55)] ring-1 ring-border sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] text-muted-3">우리의 캘린더</p><h3 className="mt-1 text-lg font-extrabold">2026년 9월</h3></div><span className="rounded-full bg-accent-soft px-3 py-1.5 text-[10px] font-bold text-accent">데이트한 날 4일</span></div><div className="mt-5 grid grid-cols-7 gap-y-2 text-center text-[10px]"><span className="text-[#bd7562]">일</span>{["월","화","수","목","금","토"].map(d=><span key={d} className="text-muted-3">{d}</span>)}{days.map(day=><span key={day} className={`relative mx-auto flex h-8 w-8 items-center justify-center rounded-xl ${day===12 ? "bg-accent font-bold text-white" : "text-muted"}`}>{day}{[3,12,21,27].includes(day)&&<i className={`absolute bottom-1 h-1 w-1 rounded-full ${day===12 ? "bg-white" : "bg-accent"}`} />}</span>)}</div><div className="mt-5 rounded-[18px] bg-accent-soft/55 p-4"><div className="flex items-center justify-between"><p className="text-sm font-extrabold text-accent">9월 12일</p><span className="text-[10px] text-muted-3">사진 4장 · 추억 1개</span></div><div className="mt-3 flex items-center gap-2 overflow-hidden text-[10px] font-semibold"><span className="shrink-0 rounded-full bg-white px-3 py-2">소소한 식탁</span><span className="text-accent/40">→</span><span className="shrink-0 rounded-full bg-white px-3 py-2">모노크림</span><span className="text-accent/40">→</span><span className="shrink-0 rounded-full bg-white px-3 py-2">작은빛 전시관</span></div></div></div>;
}

function StoryVisual({ active }: { active: number }) {
  return <div key={active} className="animate-[fade-in_.5s_ease-out] motion-reduce:animate-none">{active === 0 ? <RecordScene /> : active === 1 ? <PlaceRecommendScene /> : active === 2 ? <CourseScene /> : <CalendarScene />}</div>;
}

export function LoginLandingPreview({ interactive = false }: { interactive?: boolean }) {
  const [active, setActive] = useState(0);
  const stepRefs = useRef<Array<HTMLElement | null>>([]);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
      if (visible) setActive(Number((visible.target as HTMLElement).dataset.step));
    }, { rootMargin: "-28% 0px -42%", threshold: [0.15, 0.35, 0.6] });
    stepRefs.current.forEach((node) => node && observer.observe(node));
    return () => observer.disconnect();
  }, []);

  return <main className="min-h-screen bg-background text-foreground">
    <nav className="sticky top-0 z-50 border-b border-border/70 bg-background/88 px-5 py-3 backdrop-blur-xl sm:px-8"><div className="mx-auto flex max-w-[1180px] items-center justify-between"><img src="/brand-wordmark.png" alt="date.log — our private archive" className="h-auto w-[130px]" /><a href="#login" className="rounded-full bg-accent px-4 py-2 text-xs font-bold text-white transition hover:bg-accent-hover">로그인</a></div></nav>

    <section className="relative flex min-h-[calc(100vh-65px)] items-center overflow-hidden px-5 py-16 sm:px-8"><div className="absolute left-[8%] top-[12%] h-72 w-72 rounded-full bg-accent-soft/70 blur-3xl" /><div className="relative mx-auto grid w-full max-w-[1180px] items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-[11px] font-bold tracking-[.16em] text-accent">OUR PRIVATE ARCHIVE</p><h1 className="mt-5 text-[42px] font-black leading-[1.18] tracking-[-.045em] sm:text-[58px] lg:text-[66px]">함께한 오늘이,<br /><span className="text-accent">다음 데이트</span>가 되도록.</h1><p className="mt-7 max-w-[560px] text-[15px] leading-8 text-muted-2 sm:text-[17px]">장소와 사진, 한마디를 함께 기록해요.<br />쌓인 기록은 둘의 취향이 되고, AI는 더 우리다운 장소와 코스를 제안해요.</p><div className="mt-9 inline-flex items-center gap-3 rounded-full bg-white/75 px-5 py-3 text-[12px] font-bold text-accent ring-1 ring-border"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#10a37f] text-white"><GptMark className="h-3.5 w-3.5" /></span>둘의 기록이 쌓일수록, 추천은 더 우리답게.</div><a href="#story" className="mt-12 flex w-fit items-center gap-2 text-xs font-semibold text-muted-3">스크롤해서 알아보기 <span className="animate-bounce">↓</span></a></div><div className="hidden lg:block"><CourseScene /></div></div></section>

    <section id="story" className="border-y border-border/70 bg-[#f1eadf] px-5 sm:px-8"><div className="mx-auto grid max-w-[1180px] lg:grid-cols-[1.08fr_.92fr] lg:gap-20"><div className="hidden lg:block"><div className="sticky top-[112px] flex h-[calc(100vh-144px)] items-center"><div className="w-full rounded-[34px] bg-surface p-7 shadow-[0_30px_80px_-55px_rgba(42,61,59,.55)] ring-1 ring-border"><div className="mb-6 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[.12em] text-muted-3">HOW DATE.LOG WORKS</span><div className="flex gap-1.5">{story.map((_,i)=><span key={i} className={`h-1.5 rounded-full transition-all ${active===i ? "w-7 bg-accent" : "w-1.5 bg-border-strong"}`} />)}</div></div><StoryVisual active={active} /></div></div></div><div>{story.map((step,index)=><article key={step.eyebrow} ref={(node)=>{stepRefs.current[index]=node;}} data-step={index} className="flex min-h-[72vh] items-center py-16 lg:min-h-[88vh]"><div className="w-full"><div className="mb-8 rounded-[28px] bg-surface p-5 ring-1 ring-border lg:hidden"><StoryVisual active={index} /></div><p className={`text-[11px] font-extrabold tracking-[.12em] transition ${active===index ? "text-accent" : "text-muted-3"}`}>{step.eyebrow}</p><h2 className="mt-4 whitespace-pre-line text-[34px] font-black leading-[1.25] tracking-[-.04em] sm:text-[43px]">{step.title}</h2><p className="mt-5 max-w-[440px] text-[15px] leading-8 text-muted-2">{step.description}</p>{index===3&&<p className="mt-7 border-l-2 border-accent pl-4 text-sm font-bold leading-7 text-accent">오늘의 기록이 다음 데이트의 힌트가 되고,<br />다음 데이트는 다시 우리의 기록이 됩니다.</p>}</div></article>)}</div></div></section>

    <section id="login" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-[1000px] overflow-hidden rounded-[30px] bg-surface shadow-[0_30px_80px_-55px_rgba(42,61,59,.6)] ring-1 ring-border lg:grid-cols-[.9fr_1.1fr]"><div className="bg-accent p-8 text-white sm:p-12"><img src="/brand-wordmark.png" alt="date.log" className="h-auto w-[150px] brightness-0 invert" /><h2 className="mt-12 text-3xl font-black leading-[1.3] tracking-[-.035em]">우리만의 date.log를<br />시작해볼까요?</h2><p className="mt-5 text-sm leading-7 text-white/70">우리가 좋아했던 공간을 잊지 않고,<br />다음 데이트를 더 우리답게.</p><p className="mt-12 text-[11px] font-semibold text-white/60">🔒 둘의 기록은 연결된 커플에게만 공개됩니다.</p></div><div className="bg-white p-7 sm:p-12">{interactive ? <LoginForm embedded /> : <><p className="text-[11px] font-bold tracking-[.1em] text-accent">WELCOME BACK</p><h3 className="mt-2 text-2xl font-black">우리의 기록으로 돌아가기</h3><div className="mt-8 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-muted">이메일</span><input type="email" placeholder="이메일 주소를 입력해 주세요" className="h-12 w-full rounded-2xl border border-border bg-[#fffdfa] px-4 text-sm outline-none focus:border-accent" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-muted">비밀번호</span><input type="password" placeholder="••••••" className="h-12 w-full rounded-2xl border border-border bg-[#fffdfa] px-4 text-sm outline-none focus:border-accent" /></label><button type="button" className="h-12 w-full rounded-2xl bg-accent text-sm font-bold text-white">로그인</button></div><div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-border" /><span className="text-[10px] text-muted-3">또는</span><span className="h-px flex-1 bg-border" /></div><button type="button" className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl border border-border text-sm font-semibold"><GoogleMark />Google로 계속하기</button><p className="mt-6 text-center text-xs text-muted-2">계정이 없나요? <Link href="/signup" className="font-bold text-accent">회원가입</Link></p></>}</div></div></section>
  </main>;
}
